## 演習2_1

https://docs.python.org/ja/3.13/library/functions.html

- dir()
    - 引数がない場合、現在のローカルスコープにある名前のリストを返します。
    - 引数がある場合、そのオブジェクトの有効な属性のリストを返そうと試みます。
- id()
    - オブジェクトの "識別値" を返します。
- type()
    - オブジェクトの型を返します。

## 演習2_2

In [59]:
x = 3
print(f"type(x): {type(x)}")
print(f"id(x): {id(x)}")
print(f"dir(x): {dir(x)}")

type(x): <class 'int'>
id(x): 4370383152
dir(x): ['__abs__', '__add__', '__and__', '__bool__', '__ceil__', '__class__', '__delattr__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floor__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getnewargs__', '__gt__', '__hash__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__le__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rrshift__', '__rshift__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__trunc__', '__xor__', 'as_integer_ratio', 'bit_count', 'bit_length', 'conjugate', 'denominator', 'from_bytes', 'imag', 'numerator', 'real', 'to_bytes']

In [60]:
y = x
print(f"比較")
print(f"id(x): {id(x)}")
print(f"id(y): {id(y)}")

比較
id(x): 4370383152
id(y): 4370383152

In [61]:
y = y - 1
print(f"比較")
print(f"x: {x}")
print(f"id(x): {id(x)}")
print(f"y: {y}")
print(f"id(y): {id(y)}")

比較
x: 3
id(x): 4370383152
y: 2
id(y): 4370383120

変数yの値を変更するとidも変更される。一方xの値とid(x)は変更されなかった。yは新しいオブジェクトを参照するようになったと言える

## 演習2_3

In [62]:
import pandas as pd

### 問題1

In [63]:
pearson1 = pd.read_csv("data/pearson.csv")
pearson1

        Father       Son
0     65.04851  59.77827
1     63.25094  63.21404
2     64.95532  63.34242
3     65.75250  62.79238
4     61.13723  64.28113
...        ...       ...
1073  66.99681  70.75232
1074  71.33181  68.26774
1075  71.78314  69.30589
1076  70.73837  69.30199
1077  70.30609  67.01500

[1078 rows x 2 columns]

### 問題2

In [64]:
pearson0 = pd.read_csv("data/pearson_nh.csv")
pearson0

      65.04851  59.77827
0     63.25094  63.21404
1     64.95532  63.34242
2     65.75250  62.79238
3     61.13723  64.28113
4     63.02254  64.24221
...        ...       ...
1072  66.99681  70.75232
1073  71.33181  68.26774
1074  71.78314  69.30589
1075  70.73837  69.30199
1076  70.30609  67.01500

[1077 rows x 2 columns]

### 問題3

In [65]:
pearson2 = pd.read_csv("data/pearson_nh.csv", header=None)
pearson2

             0         1
0     65.04851  59.77827
1     63.25094  63.21404
2     64.95532  63.34242
3     65.75250  62.79238
4     61.13723  64.28113
...        ...       ...
1073  66.99681  70.75232
1074  71.33181  68.26774
1075  71.78314  69.30589
1076  70.73837  69.30199
1077  70.30609  67.01500

[1078 rows x 2 columns]

### 問題4

In [66]:
pearson3 = pd.read_csv("data/pearson_nh.csv", names=["Father", "Son"])
pearson3

        Father       Son
0     65.04851  59.77827
1     63.25094  63.21404
2     64.95532  63.34242
3     65.75250  62.79238
4     61.13723  64.28113
...        ...       ...
1073  66.99681  70.75232
1074  71.33181  68.26774
1075  71.78314  69.30589
1076  70.73837  69.30199
1077  70.30609  67.01500

[1078 rows x 2 columns]

## 演習2_4

In [67]:
pearson4 = pd.read_csv("data/pearson_indexed.csv", index_col=0)
pearson4

         Father       Son
p0001  65.04851  59.77827
p0002  63.25094  63.21404
p0003  64.95532  63.34242
p0004  65.75250  62.79238
p0005  61.13723  64.28113
...         ...       ...
p1074  66.99681  70.75232
p1075  71.33181  68.26774
p1076  71.78314  69.30589
p1077  70.73837  69.30199
p1078  70.30609  67.01500

[1078 rows x 2 columns]

## 演習2_5

### 問題1

In [68]:
pearson4.iloc[6:11]

         Father       Son
p0007  65.37053  64.08231
p0008  64.72398  63.99574
p0009  66.06509  64.61338
p0010  66.96738  63.97944
p0011  59.00800  65.24451

### 問題2

In [69]:
pearson4.iloc[:, 1]

p0001    59.77827
p0002    63.21404
p0003    63.34242
p0004    62.79238
p0005    64.28113
           ...
p1074    70.75232
p1075    68.26774
p1076    69.30589
p1077    69.30199
p1078    67.01500
Name: Son, Length: 1078, dtype: float64

### 問題3

In [70]:
pearson4.iloc[10:21, 0]

p0011    59.00800
p0012    62.93203
p0013    63.67063
p0014    64.07386
p0015    64.68851
p0016    65.15466
p0017    66.37353
p0018    65.57704
p0019    67.36765
p0020    66.75929
p0021    67.79764
Name: Father, dtype: float64

### 問題4

In [71]:
pearson4.loc["p0100":"p0110"]

         Father       Son
p0100  69.58258  68.06568
p0101  70.39517  68.38188
p0102  71.19284  67.75943
p0103  70.82429  68.59991
p0104  71.65367  67.91483
p0105  73.28133  67.83861
p0106  63.03753  68.77562
p0107  63.66428  69.60782
p0108  65.38311  69.69143
p0109  64.60205  69.41491
p0110  66.40661  69.68931

### 問題5

In [72]:
pearson4.loc["p0200":"p0210", "Father"]

p0200    70.83996
p0201    72.56944
p0202    67.93353
p0203    67.54033
p0204    72.79855
p0205    62.67482
p0206    68.19196
p0207    65.07215
p0208    73.42952
p0209    62.94125
p0210    62.53667
Name: Father, dtype: float64

### 問題6

In [73]:
pearson4[(pearson4["Father"] >= 70) & (pearson4["Father"] < 71)]

         Father       Son
p0070  70.35646  66.72679
p0071  70.00643  66.92996
p0101  70.39517  68.38188
p0103  70.82429  68.59991
p0127  70.36485  69.34638
...         ...       ...
p1049  70.70290  72.07098
p1055  70.37520  73.68578
p1062  70.95019  73.81376
p1077  70.73837  69.30199
p1078  70.30609  67.01500

[93 rows x 2 columns]

## 演習2_6

### 問題1

In [74]:
pearson4["Mother"] = 0
pearson4

         Father       Son  Mother
p0001  65.04851  59.77827       0
p0002  63.25094  63.21404       0
p0003  64.95532  63.34242       0
p0004  65.75250  62.79238       0
p0005  61.13723  64.28113       0
...         ...       ...     ...
p1074  66.99681  70.75232       0
p1075  71.33181  68.26774       0
p1076  71.78314  69.30589       0
p1077  70.73837  69.30199       0
p1078  70.30609  67.01500       0

[1078 rows x 3 columns]

### 問題2

In [75]:
pearson4.loc["p0000"] = 0
pearson4

         Father       Son  Mother
p0001  65.04851  59.77827       0
p0002  63.25094  63.21404       0
p0003  64.95532  63.34242       0
p0004  65.75250  62.79238       0
p0005  61.13723  64.28113       0
...         ...       ...     ...
p1075  71.33181  68.26774       0
p1076  71.78314  69.30589       0
p1077  70.73837  69.30199       0
p1078  70.30609  67.01500       0
p0000   0.00000   0.00000       0

[1079 rows x 3 columns]

### 問題3

In [80]:
pearson4 = pearson4.drop("Mother", axis=1)
pearson4

         Father       Son
p0001  65.04851  59.77827
p0002  63.25094  63.21404
p0003  64.95532  63.34242
p0004  65.75250  62.79238
p0005  61.13723  64.28113
...         ...       ...
p1075  71.33181  68.26774
p1076  71.78314  69.30589
p1077  70.73837  69.30199
p1078  70.30609  67.01500
p0000   0.00000   0.00000

[1079 rows x 2 columns]

### 問題4

In [81]:
pearson4 = pearson4.drop("p1078", axis=0)
pearson4

         Father       Son
p0001  65.04851  59.77827
p0002  63.25094  63.21404
p0003  64.95532  63.34242
p0004  65.75250  62.79238
p0005  61.13723  64.28113
...         ...       ...
p1074  66.99681  70.75232
p1075  71.33181  68.26774
p1076  71.78314  69.30589
p1077  70.73837  69.30199
p0000   0.00000   0.00000

[1078 rows x 2 columns]

### 問題5

In [85]:
pearson4 = pearson4.sort_values("Father", ascending=False)
pearson4

         Father       Son
p0158  75.43393  70.09077
p1064  75.17469  73.81739
p0134  74.96203  69.03281
p0639  74.94058  71.40839
p0178  74.80830  71.66455
...         ...       ...
p0854  59.63777  64.94291
p0658  59.48980  64.81735
p0867  59.48391  63.94637
p0011  59.00800  65.24451
p0000   0.00000   0.00000

[1078 rows x 2 columns]

## 演習2_7

DataFrame から列を抽出する際、`pearson1["Father"]` と `pearson1[["Father"]]` には以下のような違いがある。

### 1. 返ってくるオブジェクトの型が異なる

- `pearson1["Father"]` → **Series**（1次元のデータ構造）として返される
- `pearson1[["Father"]]` → **DataFrame**（2次元のデータ構造）のまま返される

```python
type(pearson1["Father"])    # pandas.core.series.Series
type(pearson1[["Father"]])  # pandas.core.frame.DataFrame
```

### 2. 利用できる属性・メソッドが異なる

- Series には `.name`, `.values`, `.index` などがある一方、`.columns` や 2次元的な `.shape` は持たない
- DataFrame は `.columns`, `.shape`（行数×列数の2次元）などを持ち、複数列を扱う前提のメソッドが使える

### 3. 表示形式が異なる

- Series は列名が上部に1つだけ表示され、縦にデータが並ぶ
- DataFrame は表形式（列名が横並び）で表示される

### 4. 複数列を抽出したい場合は二重かっこが必須

- `pearson1[["Father", "Son"]]` のように書くと複数列の DataFrame を取得できる
- `pearson1["Father", "Son"]` はエラーになる（タプルキーと解釈されるため）